version: '3.8'

services:
  event-store:
    image: docker.io/thenativeweb/eventsourcingdb:0.106.0
    user: "root:root"
    volumes:
      - event-data:/events
    command: "run --api-token secret --data-directory /events --http-enabled=true --https-enabled=false --with-ui"
    ports:
      - "3000:3000"

  postgres:
    image: postgres:17.1
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    command: postgres -c log_min_messages=fatal -c log_min_error_statement=fatal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - event-store
    environment:
      ESDB_SERVER_URI: http://event-store:3000
      ESDB_SERVER_API_TOKEN: secret
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_SQL_INIT_MODE: never
      SPRING_SQL_INIT_SEPARATOR: "^;"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
    ports:
      - "8080"
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-app

volumes:
  postgres_data:
  event-data: